### ISSUE TITLE
Saltong Hex layout

### ISSUE THREAD

**Issue by roytang** [carldegs/saltong#38]
Hi,

Can we follow the NYT spelling bee layout (on desktop) where the guessed words are listed on the right hand side of the page? The current version makes it super unwieldy to recall which ones you've already guessed.

Thanks!

**Comment by carldegs** [comment]
Sure Roy! I'll try to prioritize this for the next update. Just haven't got the time to implement this yet.

**Comment by carldegs** [comment]
@roytang Implementation already merged to main.

**Comment by roytang** [comment]
Thanks!
